### ISSUE TITLE
Remova diretório target do diretório di

### ISSUE THREAD

**Issue by kyriosdata** [vixtorocha/ds-2019-02#4]
O diretório "derivado" ou produzido pelo processo de build não deve fazer parte do repositório. Bem provavelmente não está usando o .gitignore em seu diretório. Não está usando uma cópia do projeto exemplo? Ou outra da sua preferência já devidamente configurado?

**Comment by vixtorocha** [comment]
Corrigido. Tava usando um projeto derivado do exemplo mas por algum motivo o .gitignore não estava correto.
